// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CenteredText: typeof import('./src/components/CenteredText.vue')['default']
    GridText: typeof import('./src/components/GridText.vue')['default']
    NavMenu: typeof import('./src/components/NavMenu.vue')['default']
    ParallaxSection: typeof import('./src/components/ParallaxSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
